[package]
name = "fib"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.12"
thousands = "0.2.0"
num-bigint = "0.4.4"
num-traits = "0.2.16"
