[package]
name = "fib"
version = "0.5.1"
edition = "2021"
license = "BSL-1.0"

[profile.release]
strip = true
lto = true
codegen-units = 1

[dependencies]
argh = "0.1.12"
colored = "2.0.4"
num-bigint = "0.4.4"
