[package]
name = "fib"
version = "0.3.1"
edition = "2021"

[profile.release]
strip = true
lto = true
codegen-units = 1

[dependencies]
argh = "0.1.12"
thousands = "0.2.0"
num-bigint = "0.4.4"
num-traits = "0.2.16"
