name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  everything:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3
    - name: build in release
      run: cargo build --release
    - name: aggressive lint with clippy
      run: cargo clippy -- -W clippy::pedantic -W clippy::nursery -W clippy::unwrap_used
    - name: run tests
      run: cargo test
      
